image: Visual Studio 2019

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: testFileUpload.sln
  verbosity: minimal

after_test: 
    - dotnet test ./testFileUpload.sln --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - C:\ProgramData\chocolatey\lib\codecov\tools\codecov.exe -f .\testFileUpload.Tests\coverage.opencover.xml -t 1015e88e-3a63-4325-b8bc-26ccb69ff525
    - C:\ProgramData\chocolatey\lib\codecov\tools\codecov.exe -f .\testFileUpload.Core.Tests\coverage.opencover.xml -t 1015e88e-3a63-4325-b8bc-26ccb69ff525